import Head from 'next/head';
import Slider from '../components/Slider';
import styles from '../styles/Home.module.css';
import ComponentsList from "../components/ComponentsList";

export const getServerSideProps = async () => {
  const resFood = await fetch(`http://localhost:3000/api/foods`);
  const resProduct = await fetch(`http://localhost:3000/api/products`);
  const Fooddata = await resFood.json();
  const Productdata = await resProduct.json();

  return {
    props: {
      foodList: Fooddata,
      productList: Productdata,
    },
  };
}; 
export default function Home({ foodList, productList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Delivery App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />
      {foodList   && <ComponentsList foodList={foodList} productList={productList} />}
      
    </div>
  );
}

 